apiVersion: v1
kind: ReplicationController
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  # Numbe of master nodes must be 3 to avoid split brain syndrome
  replicas: 3
  selector:
    component: elasticsearch
    role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        # This image omits the 'http.cors' section so it can work with Kibana.
        # See issue https://github.com/elastic/kibana/issues/6719 for details.
        image: gcr.io/vic-k8-1352/elasticsearch-k8:latest
        # image: quay.io/pires/docker-elasticsearch-kubernetes:2.3.3
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: "k8-es-cluster"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir: {}
            name: "storage"
