apiVersion: v1
kind: Service
metadata:
  name: gsk-search
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
# Comment out following line for testing direct queries    
#  type: LoadBalance
