apiVersion: v1
kind: Service
metadata:
  name: gsk-kibana
spec:
  ports:
    - port: 5601
      targetPort: http
  selector:
    component: kibana
# Comment out the following line to make Kibana private
  type: LoadBalancer
