apiVersion: v1
kind: ReplicationController
metadata:
  name: es-kibana
  labels:
    components: kibana
spec:
  replicas: 1
  selector:
    component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      serviceAccount: elasticsearch
      containers:
      - env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        image: gcr.io/PROJECT_ID/gsk-kibana
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
